# Render Blueprint for Criminal Law Knowledge Base

services:
  # Backend API (FastAPI)
  - type: web
    name: criminal-law-api
    runtime: python
    plan: free
    region: singapore
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r Backend/requirements.txt && chmod +x Backend/build.sh && ./Backend/build.sh"
    startCommand: "cd Backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false  # User must set this in Render dashboard
      - key: GROQ_API_KEY
        sync: false  # User must set this in Render dashboard
      - key: PORT
        value: 10000
    healthCheckPath: /api/v1/health

  # Frontend (React + Vite)
  - type: web
    name: criminal-law-frontend
    runtime: static
    plan: free
    region: singapore
    buildCommand: "cd Frontend && npm install && npm run build"
    staticPublishPath: Frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false  # User must set this to backend URL (e.g., https://criminal-law-api.onrender.com)
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Recommended Environment Variables to set in Render Dashboard:
# 
# For Backend (criminal-law-api):
# - DATABASE_URL: Your Supabase PostgreSQL connection string
#   Example: postgresql://postgres.PROJECT_REF:PASSWORD@aws-1-ap-south-1.pooler.supabase.com:5432/postgres
# - GROQ_API_KEY: Your Groq API key from https://console.groq.com
#
# For Frontend (criminal-law-frontend):
# - VITE_API_BASE_URL: Your backend URL from Render
#   Example: https://criminal-law-api.onrender.com
